name: 'Classic Discord Webhooks'
description: 'This GitHub Action sends simple discord messages for your commits.'

inputs:
  id:
    description: The Discord Webhook id
    required: true
  token:
    description: The Discord Webhook token
    required: true

runs:
  using: 'node12'
  main: 'src/index.js'
  
branding:
  color: black
